# Generated by Django 5.2.1 on 2025-06-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='created_at',
        ),
    ]
